### ISSUE TITLE
Rename state-conductor-flow directory

### ISSUE THREAD

**Issue by aclavio** [aclavio/marklogic-state-conductor#135]
The default location for state machine files is the `ml-data/state-conductor-flow` directory.  This directory lives in the `state-conductor-modules` and `state-conductor-example` project (others?).  This directory should be renamed according to the new naming conventions.

Options:
* state-machines
* state-machine-definitions
* state-conductor-definitions
* state-conductor-state-machines

**Comment by freshie** [comment]
created a branch for this called [feature/135-rename-state-conductor-flow-directory](https://github.com/freshie/marklogic-state-conductor/tree/feature/135-rename-state-conductor-flow-directory)
