### ISSUE TITLE
Event Based Flow Context

### ISSUE THREAD

**Issue by aclavio** [aclavio/marklogic-state-conductor#42]
Allow State Conductor Flow definitions to use an Event (see wait states) as their [context](https://github.com/aclavio/marklogic-state-conductor/wiki/Flow-File-Context).  This will allow the State Conductor to respond to activities outside of the trigger based (document insert, update, etc), such as programatic events, or rest based event emitters.

**Comment by freshie** [comment]
created a branch for the work of this issue called [feature/42-Event-Based-Flow-Context](https://github.com/freshie/marklogic-state-conductor/tree/feature/42-Event-Based-Flow-Context)
