### ISSUE TITLE
Add duration to provenance

### ISSUE THREAD

**Issue by aclavio** [aclavio/marklogic-state-conductor#81]
For each state-conductor action/condition module, add it's elapsed duration to the provenance.

**Comment by aclavio** [comment]
For v0.6.1 adding trace statements around invocations of the action module and condition module user code.

**Comment by freshie** [comment]
Created a branch for the work on this issue called [feature/81-Add-duration-to-provenance ](https://github.com/freshie/marklogic-state-conductor/tree/feature/81-Add-duration-to-provenance)
